### ISSUE TITLE
PushToDevice from TofArManager not throw error

### ISSUE THREAD

**Issue by radoslawsz** [SonySemiconductorSolutions/tof-ar-samples-basic#2]
In My Win11 computer  System.IO.Path.GetFullPath(EditorPrefs.GetString("AndroidSdkRoot")) generate error not find path
(even if I add it by RegEdit ) 

My temporary brute force solution: 
----------------------------------
29 line in EditorUtils.cs:
        public static string GetAdbPath()
        {
            //rs del            var adbPath = System.IO.Path.GetFullPath(EditorPrefs.GetString("AndroidSdkRoot"));
            var adbPath = "C:\\Program Files\\Unity\\Hub\\Editor\\2021.3.21f1\\Editor\\Data\\PlaybackEngines\\AndroidPlayer\\SDK";
-----------------------------------------------

**Comment by HirotakaGoto** [comment]
Hello radoslawsz,

Thank you very much for posting your comment on GitHub.

This issue is resolved by setting the Unity Editor.
Please find the ToF AR User Manual below for details on configuration.
https://developer.sony.com/develop/tof-ar/development-guides/docs/ToF_AR_User_Manual_en.html#_setting_up_tofarserver

Please feel free to contact us if you have problems again.

ToF AR team
